# Generated by Django 4.2.19 on 2025-03-04 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Equipamento')),
                ('valor_aquisicao', models.FloatField(verbose_name='Valor de Aquisição')),
                ('quantidade_nos', models.IntegerField(default=1, verbose_name='Quantidade de Nós')),
                ('cvc', models.FloatField(default=0, verbose_name='CVC - Custo de Verificação e Calibração')),
                ('cma', models.FloatField(default=0, verbose_name='CMA - Custo de Manutenção Anual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('peia', models.CharField(max_length=255, verbose_name='PEIA')),
                ('data_inicio', models.DateField(verbose_name='Data início')),
                ('data_fim', models.DateField(verbose_name='Data fim')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor total')),
                ('valor_financiado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor financiado')),
                ('valor_so_ptr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor SO Plano de Trabalho')),
                ('valor_funape', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Funape')),
                ('tx_adm_ue', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Tx Admin. Unidade Embrapii')),
                ('contrapartida', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Contrapartida prometida')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['data_fim'],
            },
        ),
        migrations.CreateModel(
            name='salario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês de referência')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)], verbose_name='Ano de referência')),
                ('valor', models.FloatField(blank=True, default=0, null=True)),
                ('horas', models.IntegerField(default=160)),
                ('anexo', models.BooleanField(default=False, verbose_name='Anexo')),
                ('id_pessoa', models.ForeignKey(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, to='contrapartida.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'ordering': ['id_pessoa'],
            },
        ),
        migrations.CreateModel(
            name='contrapartida_pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_alocadas', models.FloatField(verbose_name='Horas Alocadas')),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.projeto', verbose_name='Projeto')),
                ('id_salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.salario', verbose_name='Salário')),
            ],
        ),
        migrations.CreateModel(
            name='contrapartida_equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês de referência')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)], verbose_name='Ano de referência')),
                ('horas_alocadas', models.IntegerField(blank=True, null=True)),
                ('id_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.equipamento')),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.projeto')),
            ],
            options={
                'ordering': ['-ano', '-mes'],
            },
        ),
        migrations.AddConstraint(
            model_name='salario',
            constraint=models.UniqueConstraint(fields=('id_pessoa', 'mes', 'ano'), name='unique_pessoa_referencia'),
        ),
        migrations.AlterUniqueTogether(
            name='contrapartida_pesquisa',
            unique_together={('id_projeto', 'id_salario')},
        ),
    ]
