# Generated by Django 4.2.19 on 2025-02-24 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrapartidaPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_alocadas', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Equipamento')),
                ('valor_aquisicao', models.FloatField(verbose_name='Valor de Aquisição')),
                ('quantidade_nos', models.IntegerField(default=1, verbose_name='Quantidade de Nós')),
                ('cvc', models.FloatField(default=0, verbose_name='CVC - Custo de Verificação e Calibração')),
                ('cma', models.FloatField(default=0, verbose_name='CMA - Custo de Manutenção Anual')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(verbose_name='Data início')),
                ('data_fim', models.DateField(verbose_name='Data fim')),
                ('valor', models.FloatField()),
            ],
            options={
                'ordering': ['data_fim'],
            },
        ),
        migrations.CreateModel(
            name='salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=7, verbose_name='Mês de referência')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('id_pessoa', models.ForeignKey(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, to='contrapartida.pessoa', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='projetoContrapartidaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_alocacao', models.DateField(blank=True, null=True)),
                ('referencia_arrecadacao', models.DateField(blank=True, null=True)),
                ('contrapartida_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.contrapartidapessoa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.projeto')),
            ],
            options={
                'ordering': ['projeto'],
            },
        ),
        migrations.CreateModel(
            name='contrapartidaSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_financiado', models.FloatField(blank=True, null=True)),
                ('meses', models.IntegerField(blank=True, null=True)),
                ('dao_funape', models.CharField(blank=True, max_length=50, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.projeto')),
            ],
            options={
                'ordering': ['projeto'],
            },
        ),
        migrations.AddField(
            model_name='contrapartidapessoa',
            name='salario_bruto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.salario'),
        ),
        migrations.CreateModel(
            name='contrapartidaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateField(blank=True, null=True)),
                ('quantidade_hora', models.FloatField(blank=True, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.equipamento')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.projeto')),
            ],
            options={
                'ordering': ['projeto'],
            },
        ),
        migrations.AddConstraint(
            model_name='salario',
            constraint=models.UniqueConstraint(fields=('id', 'referencia'), name='unique_pessoa_referencia'),
        ),
    ]
