# Generated by Django 4.2.19 on 2025-02-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartida', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salario',
            options={'ordering': ['id_pessoa']},
        ),
        migrations.AddField(
            model_name='projeto',
            name='contrapartida_prometida',
            field=models.FloatField(default=0),
        ),
    ]
