# Generated by Django 4.2.19 on 2025-02-26 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartida', '0002_alter_salario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contrapartida_pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_alocadas', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contrapartidapessoa',
            name='salario_bruto',
        ),
        migrations.RemoveField(
            model_name='contrapartidaso',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='projetocontrapartidapesquisa',
            name='contrapartida_pesquisa',
        ),
        migrations.RemoveField(
            model_name='projetocontrapartidapesquisa',
            name='projeto',
        ),
        migrations.AddField(
            model_name='salario',
            name='horas',
            field=models.IntegerField(default=160),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor',
            field=models.FloatField(verbose_name='Valor total'),
        ),
        migrations.DeleteModel(
            name='contrapartidaEquipamento',
        ),
        migrations.DeleteModel(
            name='contrapartidaPessoa',
        ),
        migrations.DeleteModel(
            name='contrapartidaSO',
        ),
        migrations.DeleteModel(
            name='projetoContrapartidaPesquisa',
        ),
        migrations.AddField(
            model_name='contrapartida_pesquisa',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.salario'),
        ),
    ]
