# Generated by Django 4.2.19 on 2025-02-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartida', '0003_contrapartida_pesquisa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrapartida_pesquisa',
            old_name='horas_alocadas',
            new_name='horas',
        ),
    ]
