# Generated by Django 4.2.19 on 2025-02-27 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartida', '0004_rename_horas_alocadas_contrapartida_pesquisa_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrapartida_pesquisa',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contrapartida.projeto'),
            preserve_default=False,
        ),
    ]
