# Generated by Django 4.2.19 on 2025-02-27 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartida', '0005_contrapartida_pesquisa_projeto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrapartida_pesquisa',
            options={'verbose_name': 'Contrapartida Pesquisa', 'verbose_name_plural': 'Contrapartidas Pesquisas'},
        ),
        migrations.AddField(
            model_name='contrapartida_pesquisa',
            name='horas_alocadas',
            field=models.FloatField(default=0, verbose_name='Horas Alocadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrapartida_pesquisa',
            name='nome',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contrapartida.pessoa', verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrapartida_pesquisa',
            name='referencia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contrapartida.salario', verbose_name='Referência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrapartida_pesquisa',
            name='valor_hora',
            field=models.FloatField(default=0, verbose_name='Valor Hora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrapartida_pesquisa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.projeto', verbose_name='Projeto'),
        ),
        migrations.AlterUniqueTogether(
            name='contrapartida_pesquisa',
            unique_together={('projeto', 'nome', 'referencia')},
        ),
        migrations.RemoveField(
            model_name='contrapartida_pesquisa',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='contrapartida_pesquisa',
            name='valor',
        ),
    ]
