# Generated by Django 4.2.22 on 2025-06-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='declaracao_contrapartida_pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projeto', models.IntegerField(verbose_name='Projeto Id')),
                ('projeto', models.CharField(max_length=255, verbose_name='Projeto')),
                ('mes', models.IntegerField(verbose_name='Mês de referência')),
                ('ano', models.IntegerField(verbose_name='Ano de referência')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de geração da declaração')),
            ],
            options={
                'verbose_name': 'Declaração Contrapartida Pesquisa',
                'verbose_name_plural': 'Declarações Contrapartida Pesquisa',
                'db_table': 'declaracao_contrapartida_pesquisa',
                'ordering': ['-ano', '-mes', 'projeto'],
            },
        ),
        migrations.CreateModel(
            name='declaracao_contrapartida_pesquisa_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Bolsista')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('funcao', models.CharField(default='Pesquisador', max_length=100, verbose_name='Função')),
                ('horas_alocadas', models.IntegerField(verbose_name='Carga Horária Mensal')),
                ('salario', models.FloatField(verbose_name='Salário')),
                ('valor_cp', models.FloatField(verbose_name='Valor das Horas')),
                ('declaracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='declaracao.declaracao_contrapartida_pesquisa', verbose_name='Declaração')),
            ],
            options={
                'verbose_name': 'Item da Declaração Contrapartida Pesquisa',
                'verbose_name_plural': 'Itens da Declaração Contrapartida Pesquisa',
                'db_table': 'declaracao_contrapartida_pesquisa_item',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='declaracao_contrapartida_pesquisa',
            constraint=models.UniqueConstraint(fields=('id_projeto', 'mes', 'ano'), name='unique_declaracao_por_projeto_mes_ano'),
        ),
        migrations.AddConstraint(
            model_name='declaracao_contrapartida_pesquisa_item',
            constraint=models.UniqueConstraint(fields=('declaracao', 'cpf'), name='unique_item_por_declaracao_e_cpf'),
        ),
    ]
