# Generated by Django 4.2.22 on 2025-07-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracao_contrapartida_equipamento_item',
            name='descricao',
            field=models.CharField(max_length=400, null=True, verbose_name='Descricao'),
        ),
    ]
