# Generated by Django 4.2.22 on 2025-07-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracao', '0002_alter_declaracao_contrapartida_equipamento_item_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracao_contrapartida_pesquisa',
            name='codigo',
            field=models.CharField(max_length=30, null=True, verbose_name='Peia'),
        ),
        migrations.AddField(
            model_name='declaracao_contrapartida_rh',
            name='codigo',
            field=models.CharField(max_length=30, null=True, verbose_name='Peia'),
        ),
        migrations.AddField(
            model_name='declaracao_contrapartida_so',
            name='codigo',
            field=models.CharField(max_length=30, null=True, verbose_name='Peia'),
        ),
        migrations.AlterField(
            model_name='declaracao_contrapartida_equipamento_item',
            name='codigo',
            field=models.CharField(max_length=30, verbose_name='Peia'),
        ),
    ]
